principal_homepage:
    path:     /
    defaults: { _controller: principalBundle:Estudio:principal }

#quienes_somos:
#    path:     /principal
#    defaults: { _controller: principalBundle:Estudio:quienessomos }


    # principal_homepage:
      #  path:     /
      #  defaults: { _controller: principalBundle:Default:index }
